const ACTIONS = {
  addUser: "ADD_USER",
  setAlert: "SET_ALERT",
  clearAlert: "CLEAR_ALERT",
  updateProduct: "UPDATE_PRODUCT",
  logOutUser: "LOGOUT_USER",
  addToCart: "ADD_TO_CART",
  removeFromCart: "REMOVE",
  deleteCart: "DELETE",
  addToHistory: "ADD_TO_HISTORY",
  addPaymentMethod: "PAY",
  products: "PRODUCTS",
  shippingAddress: "SHIPPING",
  removeFromCart: "REMOVE_ITEM",
  userLogout: "LOGOUT",
  clearCart: "CLEAR_CART",
  saveShippingAddress: "ADD_SHIPPING_ADDRESS",
  setCurrency: "SET_CURRENCY",
  getProducts: "GET_PRODUCTS",
  setProduct: "SET_PRODUCT",
};
export default ACTIONS;
